New

In [2]:
# unzip a file
import zipfile
with zipfile.ZipFile('web-polblogs.zip', 'r') as zip_ref:
    zip_ref.extractall('web-polblogs.txt')

In [2]:
def read_mtx_file(file_path):
    with open(file_path, 'r') as file:
        # Read the lines from the file
        lines = file.readlines()

        # Extract matrix dimensions and non-zero entries
        rows, columns, non_zeros = map(int, lines[1].split())

        # Extract non-zero entries
        non_zero_entries = [line.strip().split() for line in lines[2:]]

    return rows, columns, non_zeros, non_zero_entries

def write_to_txt(rows, columns, non_zeros, non_zero_entries, output_file):
    with open(output_file, 'w') as file:
        # Write matrix dimensions and non-zero entries to the txt file
        file.write(f"{rows} {columns} {non_zeros}\n")

        # Write non-zero entries to the txt file
        for entry in non_zero_entries:
            file.write(" ".join(entry) + "\n")

# Replace 'input.mtx' and 'output.txt' with your file names
input_file = 'web-polblogs.mtx'
output_file = 'output.txt'

# Read the MatrixMarket file
rows, columns, non_zeros, non_zero_entries = read_mtx_file(input_file)

# Write the data to a text file
write_to_txt(rows, columns, non_zeros, non_zero_entries, output_file)


In [7]:
import numpy as np

# Initialize a matrix of zeros
matrix_size = 643
matrix = np.zeros((matrix_size, matrix_size))

# Read data from the text file
with open('output.txt', 'r') as file:
    lines = file.readlines()

# Process each line in the file
for line in lines:
    # Split the line into two values
    values = line.split()
    col_index = int(values[0]) - 1  # Convert to 0-based index
    row_index = int(values[1]) - 1  # Convert to 0-based index

    # Increment the corresponding element in the matrix
    matrix[row_index, col_index] += 1

# Print or use the resulting matrix as needed
print(matrix)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [8]:
# Count the number of 1s in each row
ones_count_per_row = np.sum(matrix == 1, axis=1)

# Print the result
for row_index, count in enumerate(ones_count_per_row, start=1):
    print(f"Row {row_index}: {count} 1s")

Row 1: 1 1s
Row 2: 3 1s
Row 3: 12 1s
Row 4: 1 1s
Row 5: 6 1s
Row 6: 21 1s
Row 7: 9 1s
Row 8: 7 1s
Row 9: 11 1s
Row 10: 1 1s
Row 11: 8 1s
Row 12: 2 1s
Row 13: 9 1s
Row 14: 4 1s
Row 15: 14 1s
Row 16: 13 1s
Row 17: 1 1s
Row 18: 1 1s
Row 19: 16 1s
Row 20: 2 1s
Row 21: 7 1s
Row 22: 66 1s
Row 23: 30 1s
Row 24: 3 1s
Row 25: 23 1s
Row 26: 2 1s
Row 27: 1 1s
Row 28: 2 1s
Row 29: 5 1s
Row 30: 12 1s
Row 31: 6 1s
Row 32: 44 1s
Row 33: 4 1s
Row 34: 4 1s
Row 35: 1 1s
Row 36: 5 1s
Row 37: 1 1s
Row 38: 3 1s
Row 39: 7 1s
Row 40: 26 1s
Row 41: 13 1s
Row 42: 1 1s
Row 43: 1 1s
Row 44: 3 1s
Row 45: 2 1s
Row 46: 36 1s
Row 47: 25 1s
Row 48: 1 1s
Row 49: 24 1s
Row 50: 5 1s
Row 51: 0 1s
Row 52: 4 1s
Row 53: 4 1s
Row 54: 17 1s
Row 55: 6 1s
Row 56: 1 1s
Row 57: 10 1s
Row 58: 1 1s
Row 59: 35 1s
Row 60: 6 1s
Row 61: 0 1s
Row 62: 5 1s
Row 63: 25 1s
Row 64: 15 1s
Row 65: 25 1s
Row 66: 1 1s
Row 67: 4 1s
Row 68: 3 1s
Row 69: 2 1s
Row 70: 10 1s
Row 71: 8 1s
Row 72: 2 1s
Row 73: 1 1s
Row 74: 8 1s
Row 75: 1 1s
Row 76: 4 1

In [9]:
print(np.count_nonzero(matrix))

2280


In [10]:
# Normalize the columns of the matrix for non-zero values
non_zero_columns = np.sum(matrix, axis=0) != 0
matrix[:, non_zero_columns] /= np.sum(matrix[:, non_zero_columns], axis=0)

# Print the normalized matrix
print(matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [11]:
import numpy as np

# Find columns with only zero elements
zero_columns = np.where(~matrix.any(axis=0))[0]

# Replace columns with only zero elements with 1/643
matrix[:, zero_columns] = 1/643

# Verify that the sum of each column is 1
column_sums = matrix.sum(axis=0)
print("Column Sums:", column_sums)

# Verify that the matrix is column stochastic
print("Is Column Stochastic:", np.allclose(column_sums, 1))


Column Sums: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1

In [12]:
print(np.count_nonzero(matrix))

80083


In [14]:
# Check if the sum of each column is approximately equal to 1
column_sums = matrix.sum(axis=0)
is_column_stochastic = np.allclose(column_sums, 1)

if is_column_stochastic:
    print("The matrix is column stochastic.")
else:
    print("The matrix is not column stochastic.")

The matrix is column stochastic.


In [13]:
L = matrix
print(L)

[[0.00155521 0.00155521 0.00155521 ... 0.         0.         0.        ]
 [0.00155521 0.00155521 0.00155521 ... 0.         0.         0.        ]
 [0.00155521 0.00155521 0.00155521 ... 0.         0.         0.        ]
 ...
 [0.00155521 0.00155521 0.00155521 ... 0.         0.         0.        ]
 [0.00155521 0.00155521 0.00155521 ... 0.         0.         0.        ]
 [0.00155521 0.00155521 0.00155521 ... 0.         0.         0.        ]]


Playground

In [10]:
import numpy as np

# Example: Creating an example graph with 5 vertices
num_vertices = 5

# Define the edges of the graph (example structure)
edges = [(1, 2), (1, 3), (2, 3), (3, 4), (4, 5), (5, 1)]

# Create an adjacency matrix
adjacency_matrix = np.zeros((num_vertices, num_vertices))

# Populate the adjacency matrix based on the edges
for edge in edges:
    adjacency_matrix[edge[0] - 1, edge[1] - 1] = 1

# Make the matrix column stochastic
column_stochastic_matrix = adjacency_matrix / adjacency_matrix.sum(axis=0, keepdims=True)

print("Adjacency Matrix:")
print(adjacency_matrix)
print("\nColumn Stochastic Matrix:")
print(column_stochastic_matrix)

Adjacency Matrix:
[[0. 1. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]

Column Stochastic Matrix:
[[0.  1.  0.5 0.  0. ]
 [0.  0.  0.5 0.  0. ]
 [0.  0.  0.  1.  0. ]
 [0.  0.  0.  0.  1. ]
 [1.  0.  0.  0.  0. ]]


In [15]:
import numpy as np

def page_rank(matrix, damping_factor=0.85, epsilon=1e-8, max_iterations=1000):
    """
    PageRank algorithm implementation.

    Parameters:
    - matrix: The column stochastic matrix representing the transition probabilities.
    - damping_factor: The damping factor (typically set to 0.85).
    - epsilon: Convergence criterion.
    - max_iterations: Maximum number of iterations.

    Returns:
    - page_ranks: A 1D array containing the PageRank scores for each vertex.
    """

    # Get the number of vertices
    num_vertices = matrix.shape[0]

    # Initialize PageRank scores
    page_ranks = np.ones(num_vertices) / num_vertices

    for _ in range(max_iterations):
        # Store the current PageRank scores for convergence check
        old_page_ranks = page_ranks.copy()

        # Update PageRank scores
        page_ranks = (1 - damping_factor) / num_vertices + damping_factor * np.dot(matrix, page_ranks)

        # Check for convergence
        if np.linalg.norm(page_ranks - old_page_ranks, 1) < epsilon:
            break

    return page_ranks

# Assuming you have the column stochastic matrix L
# Compute PageRank scores
page_ranks = page_rank(L)

# Print the results
print("PageRank Scores:")
print(page_ranks)


PageRank Scores:
[0.00062279 0.00316637 0.00652361 0.0006862  0.00952117 0.00997297
 0.00954993 0.00171285 0.01135326 0.0011205  0.00544819 0.0008219
 0.0060065  0.00428767 0.00665065 0.00331808 0.00370566 0.00083916
 0.00316586 0.00108558 0.0056759  0.02192198 0.01202194 0.0025566
 0.00690452 0.00093014 0.00192295 0.000843   0.00160816 0.00233863
 0.00391988 0.01002537 0.00195119 0.00233928 0.00133529 0.00159132
 0.00078015 0.00175393 0.00493491 0.00548483 0.00206429 0.00248082
 0.0011205  0.00162289 0.00106966 0.00734752 0.00535326 0.00072041
 0.00691987 0.00177053 0.00060005 0.00211912 0.00215617 0.00454794
 0.00171847 0.00085507 0.00223811 0.00078015 0.00658907 0.0011999
 0.00060005 0.00107004 0.00450233 0.00296679 0.00321703 0.00105202
 0.00155635 0.00111659 0.00143939 0.00246454 0.00147206 0.00093722
 0.00083055 0.00128774 0.00111009 0.0012453  0.00119335 0.0022365
 0.00114035 0.00245185 0.00060005 0.00083055 0.00129549 0.00087948
 0.00133348 0.00060005 0.00082039 0.00091553 0.00

In [19]:
print(matrix)

[[0.00155521 0.00155521 0.00155521 ... 0.         0.         0.        ]
 [0.00155521 0.00155521 0.00155521 ... 0.         0.         0.        ]
 [0.00155521 0.00155521 0.00155521 ... 0.         0.         0.        ]
 ...
 [0.00155521 0.00155521 0.00155521 ... 0.         0.         0.        ]
 [0.00155521 0.00155521 0.00155521 ... 0.         0.         0.        ]
 [0.00155521 0.00155521 0.00155521 ... 0.         0.         0.        ]]


In [16]:
# Rank the vertices in descending order
ranked_vertices = np.argsort(page_ranks)[::-1]

# Add 1 to each ranked vertex as we assumed a zero indexed graph
ranked_vertices = ranked_vertices + 1

print("Ranked Vertices:", ranked_vertices)

Ranked Vertices: [318 275  22 266 391 283  23 267   9  32   6   7   5  46 383  49  25 279
  15 274  59   3 285  13 335  21  40  11 315  47 115 278  39 150 273 314
  54  63 211 277  14 410  31  17 288 407 340 289 282  16 439 303 270 312
 305 290 276 317 304 281  65 161   2  19 415 324 309  64 319 328 184 207
  24  42  70  80 357 172 272 133 294  34  30 284 120 500 140  57  78 370
  53 192  52 124  41 175 308 223 138 155  33  27 126 479 464 110 476 339
  50 327  38 457  55   8 375 301 351 384  44  29 341  36 353 166 106  93
  67 298 413 271 356 299 345  71 167 344 297 114 174 168  69 358 507 467
 182 173 473 141 490 269  96 343 255  35  85 337 364 379 177 369  83  74
 508 414 151 259 320 336 368 445 179  76 509 311 165 417 176  60 121  77
 423 119 409 474 208 451 495 313 387 419  79 186 196 352 437 118  43  10
  68 169 416  75 536 132 501  95 224  20 386 514  62  45 268 105 390  66
 286 295 366 296 316 418 302 325 435 463 200 422 444 108  94 136 154 398
 280 332 468 392 513 190 331 582  

In [17]:
# Top n imp vertices

top_n = 5  # Change this to the desired number of top vertices
top_vertices = ranked_vertices[:top_n]
print("Top", top_n, "Vertices:", top_vertices)


Top 5 Vertices: [318 275  22 266 391]
